<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 6.0.2 (Python 3.9.13 on win32)" generated="20230125 16:27:12.745" rpa="false" schemaversion="3">
<suite id="s1" name="Demo1" source="C:\Users\40032431\Documents\Robot_Project\Assesment\Demo1.robot">
<test id="s1-t1" name="TC5" line="4">
<kw name="Open Application" library="AppiumLibrary">
<arg>remote_url=http://localhost:4723/wd/hub</arg>
<arg>platformName=android</arg>
<arg>deviceName=vivo1920</arg>
<arg>appPackage=com.tellapp</arg>
<arg>appActivity=com.tellapp.MainActivity</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/server-args.md
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<kw name="Capture Page Screenshot" library="AppiumLibrary">
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<msg timestamp="20230125 16:27:32.595" level="FAIL">No application is open</msg>
<status status="FAIL" starttime="20230125 16:27:32.595" endtime="20230125 16:27:32.598"/>
</kw>
<msg timestamp="20230125 16:27:32.603" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg timestamp="20230125 16:27:32.603" level="FAIL">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at UIA2Proxy.command (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
    at runMicrotasks (&lt;anonymous&gt;)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
    at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:244:28)
    at AndroidUiautomator2Driver.createSession (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:230:7)
    at AppiumDriver.createSession (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\lib\appium.js:387:35)</msg>
<status status="FAIL" starttime="20230125 16:27:13.001" endtime="20230125 16:27:32.603"/>
</kw>
<kw name="Set Appium Timeout" library="AppiumLibrary">
<arg>30s</arg>
<doc>Sets the timeout in seconds used by various keywords.</doc>
<status status="NOT RUN" starttime="20230125 16:27:32.603" endtime="20230125 16:27:32.603"/>
</kw>
<kw name="Wait Until Page Contains Element" library="AppiumLibrary">
<arg>xpath=//android.widget.TextView[@text='Get started']</arg>
<doc>Waits until element specified with `locator` appears on current page.</doc>
<status status="NOT RUN" starttime="20230125 16:27:32.603" endtime="20230125 16:27:32.603"/>
</kw>
<kw name="Click Element" library="AppiumLibrary">
<arg>xpath=//android.widget.TextView[@text='Get started']</arg>
<doc>Click element identified by `locator`.</doc>
<status status="NOT RUN" starttime="20230125 16:27:32.603" endtime="20230125 16:27:32.603"/>
</kw>
<status status="FAIL" starttime="20230125 16:27:13.001" endtime="20230125 16:27:32.607">WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Could not proxy command to the remote server. Original error: socket hang up
    at UIA2Proxy.command (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-base-driver\lib\jsonwp-proxy\proxy.js:274:13)
    at runMicrotasks (&lt;anonymous&gt;)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at AndroidUiautomator2Driver.commands.getDevicePixelRatio (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\commands\viewport.js:14:10)
    at AndroidUiautomator2Driver.fillDeviceDetails (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:244:28)
    at AndroidUiautomator2Driver.createSession (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\node_modules\appium-uiautomator2-driver\lib\driver.js:230:7)
    at AppiumDriver.createSession (C:\Users\40032431\Components\Appium-Server-GUI-windows-1.22.3-4\resources\app\node_modules\appium\lib\appium.js:387:35)</status>
</test>
<status status="FAIL" starttime="20230125 16:27:12.745" endtime="20230125 16:27:32.607"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Demo1">Demo1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230125 16:27:32.603" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
230125 16:27:31.116" endtime="20230125 16:27:31.116"/>
</kw>
<status status="FAIL" starttime="20230125 16:27:15.937" endtime="20230125 16:27:31.116">InvalidSessionIdException: Message: The session identified by 31576029-3f98-4739-a44c-b6f8d91fbcd8 is not known
Stacktrace:
io.appium.uiautomator2.common.exceptions.NoSuchDriverException: The session identified by 31576029-3f98-4739-a44c-b6f8d91fbcd8 is not known
	at io.appium.uiautomator2.handler.request.SafeRequestHandler.handle(SafeRequestHandler.java:54)
	at io.appium.uiautomator2.server.AppiumServlet.handleRequest(AppiumServlet.java:266)
	at io.appium.uiautomator2.server.AppiumServlet.handleHttpRequest(AppiumServlet.java:260)
	at io.appium.uiautomator2.http.ServerHandler.channelRead(ServerHandler.java:68)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMes...
    [ Message content over the limit has been removed. ]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:611)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:466)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:438)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:922)</status>
</test>
<status status="FAIL" starttime="20230125 16:27:15.571" endtime="20230125 16:27:31.116"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Demo1">Demo1</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20230125 16:27:31.108" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
